[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hooks_file = '$BASE_DIR/dpp/ddc.vim'
build = 'git update-index --skip-worktree denops/ddc/_mods.js'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
hooks_file = '$BASE_DIR/dpp/pum.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'hrsh7th/completion-snippet'
merged = 0

[[plugins]]
repo = 'Shougo/ddc-source-omni'
on_source = 'ddc.vim'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'

[[plugins]]
repo = 'yuki-yano/tsnip.nvim'
on_source = 'ddc.vim'
if = "has('nvim')"
hook_add = '''
  let g:tsnip_snippet_dir = $HOME .. '/.config/nvim/tsnip'
'''

[[plugins]]
repo = 'gamoutatsumi/ddc-sorter_ascii'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_truncate_abbr'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-copilot'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/denippet.vim'
hooks_file = "$BASE_DIR/dpp/denippet.lua"
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_lua = 'ddc_source_lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'
on_lua = 'ddc_source_lsp_setup'
