[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_post_source = '''
  call popup_preview#enable()
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
function! CommandlinePre() abort
    cnoremap <Tab>   <Cmd>call pum#map#insert_relative(+1)<CR>
    cnoremap <S-Tab> <Cmd>call pum#map#insert_relative(-1)<CR>
    cnoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
    cnoremap <C-y>   <Cmd>call pum#map#confirm()<CR>

    autocmd User DDCCmdlineLeave ++once call CommandlinePost()

    " Enable command line completion for the buffer
    call ddc#enable_cmdline_completion()
endfunction
function! CommandlinePost() abort
    silent! cunmap <Tab>
    silent! cunmap <S-Tab>
    silent! cunmap <C-e>
    silent! cunmap <CR>
endfunction
nnoremap :       <Cmd>call CommandlinePre()<CR>:
'''
hook_post_source = '''
  " pum.vim
  imap <silent><expr> <TAB> pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' : vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<TAB>'
  imap <silent><expr> <C-n> pum#visible() ? '<Cmd>call pum#map#select_relative(+1)<CR>' : '<Cmd>call ddc#map#manual_complete()<CR><Cmd>call pum#map#select_relative(+1)<CR>'
  smap <silent><expr> <TAB> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<TAB>'
  imap <silent><expr> <S-TAB> pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' : vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-TAB>'
  imap <silent><expr> <C-p> pum#visible() ? '<Cmd>call pum#map#select_relative(-1)<CR>' : '<Cmd>call ddc#map#manual_complete()<CR><Cmd>call pum#map#select_relative(-1)<CR>'
  smap <silent><expr> <S-TAB> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-TAB>'

  " ddc.vim
  call ddc#custom#patch_global('ui', 'pum')
  call ddc#custom#patch_global('autoCompleteEvents',
    \ ['InsertEnter', 'TextChangedI', 'TextChangedP', 'CmdlineChanged'])
  call ddc#custom#patch_global('cmdlineSources', { ':': ['cmdline', 'cmdline-history', 'around'] })
  call ddc#custom#patch_global('sources', ['tsnip', 'vsnip', 'nvim-lsp', 'file', 'around'])
  call ddc#custom#patch_global('keywordPattern', '(\k|-|_)*')
  call ddc#custom#patch_global('sourceOptions', {
  \ '_': { 'matchers': ['matcher_fuzzy'], 'sorters': ['sorter_fuzzy'], 'converters': ['converter_fuzzy'] },
  \ 'nvim-lsp': {
  \   'mark': 'lsp',
  \   'forceCompletionPattern': '\.\w*|:\w*|->\w*|"\w*|\\\w*|\+\w*|\/\w*',
  \   'ignoreCase': v:true,
  \   'isVolatile': v:true
  \ },
  \ 'around': {
  \   'mark': 'A',
  \   'isVolatile': v:true,
  \ },
  \ 'vsnip': {
  \   'mark': 'VS',
  \   'dup': v:true,
  \ },
  \ 'tsnip' : {
  \   'mark': 'TS',
  \   'dup': v:true,
  \ },
  \ 'file': {
  \   'mark': 'F',
  \   'isVolatile': v:true,
  \   'forceCompletionPattern': '\S/\S*',
  \   'converters': [],
  \ },
  \ 'omni': {
  \   'mark': 'O',
  \ },
  \ 'cmdline': {
  \   'mark': 'C',
  \ },
  \ })
  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = '''
  let g:vsnip_snippet_dirs = get(g:, 'vsnip_snippet_dirs', [])
  let g:vsnip_snippet_dirs += [join([$XDG_CONFIG_HOME, 'nvim', 'vsnip'], '/')]
'''

[[plugins]]
repo = 'hrsh7th/completion-snippet'
merged = 0

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
hook_add = '''
  autocmd User PumCompleteDone call vsnip_integ#on_complete_done(g:pum#completed_item)
'''

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'
hook_post_source = '''
call ddc#custom#patch_filetype(['sql', 'mysql', 'plsql'], #{
    \	sources: ['omni'],
    \	sourceOptions: #{
    \ 		omni: #{
    \			mark: 'O',
    \ 			isVolatile: v:true,
    \   		omnifunc: 'vim_dadbod_completion#omni',
    \ 		},
    \	},
    \	keywordPattern: '\w+|\.|"|\[|`'
    \ })
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'yuki-yano/tsnip.nvim'
if = "has('nvim')"
hook_add = '''
  let g:tsnip_snippet_dir = $HOME .. '/.config/nvim/tsnip'
'''

[[plugins]]
repo = 'gamoutatsumi/ddc-sorter_ascii'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
