[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_post_source = '''
  call popup_preview#enable()
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
hooks_file = ['$BASE_DIR/dein/ddc.vim', '$BASE_DIR/dein/ddc.lua']

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'Shougo/pum.vim'
hooks_file = '$BASE_DIR/dein/pum.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = '''
  let g:vsnip_snippet_dirs = get(g:, 'vsnip_snippet_dirs', [])
  let g:vsnip_snippet_dirs += [join([$XDG_CONFIG_HOME, 'nvim', 'vsnip'], '/')]
'''

[[plugins]]
repo = 'hrsh7th/completion-snippet'
merged = 0

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'

[[plugins]]
repo = 'Shougo/ddc-source-omni'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'yuki-yano/tsnip.nvim'
if = "has('nvim')"
hook_add = '''
  let g:tsnip_snippet_dir = $HOME .. '/.config/nvim/tsnip'
'''

[[plugins]]
repo = 'gamoutatsumi/ddc-sorter_ascii'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
