[[plugins]]
repo = 'Shougo/ddu.vim'
hooks_file = '$BASE_DIR/dein/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
hook_add = '''
  "nnoremap <silent> <C-e> <Cmd>call ddu#start({'ui': 'filer', 'sources': [{'name': 'file', 'params': {}}], 'sourceOptions': {'_': {'columns': ['icon_filename']}}, 'kindOptions': {'file': { 'defaultAction': 'open' }}})<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-column-filename'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'kuuote/ddu-source-mr'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'

[[plugins]]
repo = 'Milly/ddu-filter-kensaku'

[[plugins]]
repo = 'kuuote/ddu-filter-fuse'

[[plugins]]
repo = 'Milly/ddu-filter-merge'

[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'uga-rosa/ddu-filter-converter_devicon'

[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'

[[plugins]]
repo = 'kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'tennashi/ddu-source-git'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
