[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_func = ['ddu#start']
hook_source = '''
  call ddu#custom#patch_global({
  \ 'ui': 'ff',
  \ 'sourceOptions': {
  \   '_': {
  \     'ignoreCase': v:true,
  \     'matchers': ['matcher_fzf'],
  \   },
  \ },
  \ 'uiParams': {
  \   'ff': {
  \      'startFilter': v:true,
  \    }
  \ },
  \ 'kindOptions': {
  \   'file': {
  \     'defaultAction': 'open',
  \   },
  \ },
  \ 'filterParams': {
  \   'matcher_fzf': {
  \     'highlightMatched': 'Search',
  \  },
  \ },
  \ })
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = ['ddu.vim']

[plugins.ftplugin]
ddu-ff = '''
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  setlocal cursorline
'''
ddu-ff-filter = '''
  inoremap <buffer><silent> <CR> <Esc><Cmd>call ddu#ui#ff#close()<CR>
  nnoremap <buffer><silent> <CR> <Cmd><Cmd>call ddu#ui#ff#close()<CR>
'''

[[plugins]]
repo = 'gamoutatsumi/ddu-source-nvim-lsp'
on_source = 'ddu.vim'
hook_add = '''
  nnoremap <silent> ;d <Cmd>call ddu#start({ 'sources': [{ 'name': 'nvim_lsp_diagnostic_all' }] })<CR>
'''

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'
hook_add = '''
  nnoremap <silent> ;b <Cmd>call ddu#start({ 'sources': [{ 'name': 'buffer' }] })<CR>
'''

[[plugins]]
repo = 'shun/ddu-source-rg'
depends = 'ddu.vim'
on_func = ['ddu_rg#find']
hook_add = '''
  nnoremap <silent> ;g <Cmd>call ddu_rg#find()<CR>
'''

[[plugins]]
repo = 'kuuote/ddu-source-mr'
on_source = 'ddu.vim'
hook_add = '''
  nnoremap <silent> ;mu <Cmd>call ddu#start({ 'sources': [{ 'name': 'mr', 'params': { 'kind': 'mru', 'current': v:true } }] })<CR>
  nnoremap <silent> ;mw <Cmd>call ddu#start({ 'sources': [{ 'name': 'mr', 'params': { 'kind': 'mrw', 'current': v:true } }] })<CR>
'''

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'
hook_add = '''
  nnoremap <silent> ;f <Cmd>call ddu#start({ 'sources': [{'name': 'file_external'}] })<CR>
'''
hook_post_source = '''
  call ddu#custom#patch_global('sourceParams', {
  \ 'file_external': {'cmd': ['git', 'ls-files', '--exclude-standard', '-c', '-o']},
  \ })
'''
