[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_add = '''
  if !exists('g:nvui')
    let g:nightflyTransparent = 1
  endif
  colorscheme nightfly
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:WebDevIconsNerdTreeBeforeGlyphPadding=''
  let g:WebDevIconsUnicodeDecorateFolderNodes=v:true
  if exists('g:loaded_webdevicons')
    webdevicons#refresh()
  endif
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch'

#[[plugins]]
#repo = 'edkolev/tmuxline.vim'
#hook_add = '''
#let g:tmuxline_preset = {
  #\ 'a': '[#S:#I:#P]',
  #\ 'win': ['#I', '#{?#{m:ssh,#W},#{ssh-host},#W} #F'],
  #\ 'cwin': ['#I','#{?#{m:ssh,#W},#{ssh-host},#W} #F'],
  #\ 'y': ['%Y-%m-%d', '%H:%M'],
  #\ 'options': {
    #\ 'status': 'on',
    #\ 'status-left-style': 'none',
    #\ 'status-right-style': 'none',
    #\ 'status-right-length': '100',
    #\ 'status-left-length': '100',
  #\   }
  #\ }
#let g:tmuxline_status_justify = 'left'
#'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
type__depth = '1'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hooks_file = '$BASE_DIR/dein/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo = 'arthurxavierx/vim-caser'
hook_add = '''
  let g:caser_no_mappings = 1
  nmap gs_ <Plug>CaserSnakeCase
  nmap gsc <Plug>CaserCamelCase
  nmap gsm <Plug>CaserMixedCase
'''

[[plugins]]
repo = 'vimpostor/vim-tpipeline'
hook_add = '''
  let g:tpipeline_autoembed = 0
  au FocusGained * ++once call tpipeline#initialize()
'''

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = '''
  let g:localvimrc_persistent = 1
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'skk-dev/dict'
if = 0
