[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
hooks_file = '$BASE_DIR/dpp/skkeleton.vim'

[[plugins]]
repo = 'gamoutatsumi/gyazoupload.vim'
hook_add = '''
  let g:gyazo#token=$GYAZO_TOKEN
'''

[[plugins]]
repo = 'kat0h/bufpreview.vim'
build = 'deno task prepare'

[[plugins]]
repo = 'skanehira/denops-docker.vim'

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
hook_add = '''
  nnoremap gfs <Cmd>FuzzyMotion<CR>
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'

[[plugins]]
repo = 'skanehira/k8s.vim'
on_path = ['k8s://*']

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
hook_add = '''
let g:kensaku_disable_v3_migration_warning = 1
'''

[[plugins]]
repo = 'tani/vim-glance'
hook_add = '''
let g:glance#config = expand('$BASE_DIR/glance/init.ts')
'''
