[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
hooks_file = '$BASE_DIR/dein/skkeleton.vim'

[[plugins]]
repo = 'gamoutatsumi/gyazoupload.vim'
hook_add = '''
  let g:gyazo#token=$GYAZO_TOKEN
'''

[[plugins]]
repo = 'kat0h/bufpreview.vim'
build = 'deno task prepare'

# [[plugins]]
# repo = 'skanehira/denops-gh.vim'
# hook_add = '''
#   augroup gh_autocmd
#     autocmd!
#     autocmd User gh_open_issue call s:enable_auto_completion()
#   augroup END
#   function! s:enable_auto_completion()
#     " Enable source 'gh_issues' to current buffer.
#     call ddc#custom#patch_buffer('sources', ['gh_issues'])
#     call ddc#custom#patch_buffer('sourceOptions', {
#           \ 'gh_issues': {
#             \  'matcherKey': 'menu'
#           \ }})
#     call ddc#custom#patch_buffer('specialBufferCompletion', v:true)
#     " If matsui54/denops-popup-preview.vim is installed,
#     " you can preview issue body's info.
#     call popup_preview#enable()
#     " remove 'preview' from completeopt
#     set completeopt-=preview
#   endfunction
# '''

[[plugins]]
repo = 'skanehira/denops-docker.vim'

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
hook_add = '''
  nnoremap gfs <Cmd>FuzzyMotion<CR>
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'

# [[plugins]]
# repo = 'skanehira/denops-twihi.vim'

[[plugins]]
repo = 'skanehira/k8s.vim'
on_path = ['k8s://*']

# [[plugins]]
# repo = 'skanehira/denops-silicon.vim'
# hook_add = '''
#   let g:silicon_options = {
#         \  'font': 'HackGen Console NF',
#         \  'no_line_number': v:false,
#         \  'no_round_corner': v:false,
#         \  'no_window_controls': v:false,
#         \  'background_color': '#aaaaff',
#         \  'line_offset': 1,
#         \  'line_pad': 2,
#         \  'pad_horiz': 80,
#         \  'pad_vert': 100,
#         \  'shadow_blur_radius': 0,
#         \  'shadow_color': '#555555',
#         \  'shadow_offset_x': 0,
#         \  'shadow_offset_y': 0,
#         \  'tab_width': 4,
#         \  'theme': 'Solarized (dark)',
#         \ }
# '''

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
hook_add = '''
let g:kensaku_disable_v3_migration_warning = 1
'''

[[plugins]]
repo = 'tani/vim-glance'
hook_add = '''
let g:glance#config = expand('$BASE_DIR/glance/init.ts')
'''
