[[plugins]]
repo = 'Shougo/dpp.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
on_source = 'dpp.vim'
