[[plugins]]
repo = 'tversteeg/registers.nvim'
on_event = 'VimEnter'
lua_post_source = '''
require('registers').setup {}
'''

# [[plugins]]
# repo = 'kevinhwang91/nvim-hlslens'
# hook_add = '''
# noremap <silent> n <Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>
# noremap <silent> N <Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>
# noremap * *<Cmd>lua require('hlslens').start()<CR>
# noremap # #<Cmd>lua require('hlslens').start()<CR>
# noremap g* g*<Cmd>lua require('hlslens').start()<CR>
# noremap g# g#<Cmd>lua require('hlslens').start()<CR>
# nnoremap <silent> <Esc><Esc> <Cmd>nohlsearch<CR>
# '''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lazy = false
hooks_file = '$BASE_DIR/dpp/gitsigns.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lazy = false
hooks_file = '$BASE_DIR/dpp/lualine.lua'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
lazy = false

[[plugins]]
repo = 'romgrk/barbar.nvim'
lazy = false
hooks_file = ["$BASE_DIR/dpp/barbar.vim", "$BASE_DIR/dpp/barbar.lua"]

[[plugins]]
repo = 'nvim-lua/popup.nvim'
lazy = false

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
lazy = false

[[plugins]]
repo = 'phaazon/hop.nvim'
lazy = false
hooks_file = '$BASE_DIR/dpp/hop.lua'

[[plugins]]
repo = 'kwkarlwang/bufresize.nvim'
lazy = false

[[plugins]]
repo = 'aserowy/tmux.nvim'
lazy = false
lua_add = '''
require('tmux').setup({
  navigation = {
    enable_default_keybindings = true,
  },
  copy_sync = {
    enable = false,
  },
})
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'
on_event = ["VimEnter"]

[[plugins]]
repo = 'zah/nim.vim'
lazy = false

[[plugins]]
repo = 'gamoutatsumi/orgmode'
lazy = false
rev = 'feature/support-emacsclient'
lua_add = '''
require('orgmode').setup_ts_grammar()
require('orgmode').setup {
  org_agenda_files = {'~/Google Drive/マイドライブ/org/*', '~/Repositories/github.com/gamoutatsumi/my-orgs/**/*'},
  org_default_notes_file = '~/Google Drive/マイドライブ/org/refile.org',
}
'''

[[plugins]]
repo = 'levouh/tint.nvim'
lazy = false
lua_add = '''
require('tint').setup {}
'''

[[plugins]]
repo = 'uga-rosa/ccc.nvim'
on_ft = ["css", "html"]
lua_post_source = '''
require('ccc').setup {}
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
on_event = ["VimEnter"]
lua_post_source = '''
  require('notify').setup {
    background_colour = "#000000",
  }
'''

[[plugins]]
repo = 'folke/noice.nvim'
on_event = ["VimEnter"]
depends = ['nui.nvim', 'nvim-notify']
hooks_file = "$BASE_DIR/dpp/noice.lua"

[[plugins]]
repo = 'monaqa/dial.nvim'
on_map = '<Plug>(dial-'
hooks_file = ['$BASE_DIR/dpp/dial.vim']

[[plugins]]
repo = 'ray-x/guihua.lua'
lazy = false

[[plugins]]
repo = 'ruifm/gitlinker.nvim'
lazy = false
lua_add = '''
require('gitlinker').setup()
'''

[[plugins]]
repo = 'stevearc/aerial.nvim'
lazy = false
hooks_file = '$BASE_DIR/dpp/aerial.lua'

[[plugins]]
repo = 'tani/podium'
lazy = false
lua_add = '''
vim.api.nvim_create_user_command("Podium", function()
  local podium = require("podium")
  local lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)
  local output = podium.process(podium.html, table.concat(lines, "\n"))
  vim.api.nvim_buf_set_lines(0, 0, -1, true, vim.split(output, "\n"))
  vim.api.nvim_set_option_value("modified", false, { buf = 0 })
  vim.api.nvim_set_option_value("filetype", "html", { buf = 0 })
end, {})
'''

[[plugins]]
repo = 'uga-rosa/translate.nvim'
lazy = false
lua_add = '''
require("translate").setup {
   default = {
      command = "google",
      output = "floating",
      parse_after = "head"
   }
}
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lazy = false
hooks_file = ["$BASE_DIR/dpp/indent_blankline.lua"]

[[plugins]]
repo = 'numToStr/Comment.nvim'
lazy = false
hooks_file = ['$BASE_DIR/dpp/comment.lua']

[[plugins]]
repo = 'lewis6991/hover.nvim'
lazy = false
hooks_file = ['$BASE_DIR/dpp/hover.lua']

[[plugins]]
repo = 'bakpakin/Fennel'
lazy = false
rev = '1.3.1'
rtp = 'nvim'
build = 'mkdir -p nvim/lua && make LUA="nvim -ll" fennel.lua && mv fennel.lua nvim/lua/fennel.lua'
