[[plugins]]
repo = 'tversteeg/registers.nvim'
lua_post_source = '''
require('registers').setup {}
'''

[[plugins]]
repo = 'folke/which-key.nvim'

# [[plugins]]
# repo = 'kevinhwang91/nvim-hlslens'
# hook_add = '''
# noremap <silent> n <Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>
# noremap <silent> N <Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>
# noremap * *<Cmd>lua require('hlslens').start()<CR>
# noremap # #<Cmd>lua require('hlslens').start()<CR>
# noremap g* g*<Cmd>lua require('hlslens').start()<CR>
# noremap g# g#<Cmd>lua require('hlslens').start()<CR>
# nnoremap <silent> <Esc><Esc> <Cmd>nohlsearch<CR>
# '''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hooks_file = '$BASE_DIR/dein/gitsigns.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hooks_file = '$BASE_DIR/dein/lualine.lua'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
hooks_file = ["$BASE_DIR/dein/barbar.lua","$BASE_DIR/dein/barbar.vim"]

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'phaazon/hop.nvim'
hooks_file = '$BASE_DIR/dein/hop.lua'

[[plugins]]
repo = 'b3nj5m1n/kommentary'
lua_post_source = '''
require('kommentary.config').configure_language("typescriptreact", {
  single_line_comment_string = "//",
  multi_line_comment_strings = {"{/*", "*/}"}
})
'''

[[plugins]]
repo = 'kwkarlwang/bufresize.nvim'

[[plugins]]
repo = 'aserowy/tmux.nvim'
lua_post_source = '''
require('tmux').setup({
  navigation = {
    enable_default_keybindings = true,
  },
  copy_sync = {
    enable = false,
  },
})
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'zah/nim.vim'

[[plugins]]
repo = 'gamoutatsumi/orgmode'
rev = 'feature/support-emacsclient'
lua_post_source = '''
require('orgmode').setup_ts_grammar()
require('orgmode').setup {
  org_agenda_files = {'~/Google Drive/マイドライブ/org/*', '~/Repositories/github.com/gamoutatsumi/my-orgs/**/*'},
  org_default_notes_file = '~/Google Drive/マイドライブ/org/refile.org',
}
'''

[[plugins]]
repo = 'levouh/tint.nvim'
lua_post_source = '''
require('tint').setup {}
'''

[[plugins]]
repo = 'uga-rosa/ccc.nvim'
lua_post_source = '''
require('ccc').setup {}
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
lua_post_source = '''
  require('notify').setup {
    background_colour = "#000000",
  }
'''

[[plugins]]
repo = 'folke/noice.nvim'
lazy = 1
on_event = ["VimEnter"]
depends = ['nui.nvim', 'nvim-notify']
hooks_file = "$BASE_DIR/dein/noice.lua"

[[plugins]]
repo = 'j-hui/fidget.nvim'
rev = 'legacy'
lua_post_source = '''
require('fidget').setup {}
'''

[[plugins]]
repo = 'monaqa/dial.nvim'
hooks_file = ['$BASE_DIR/dein/dial.lua']

[[plugins]]
repo = 'ray-x/guihua.lua'

[[plugins]]
repo = 'ruifm/gitlinker.nvim'
lua_post_source = '''
require('gitlinker').setup()
'''

[[plugins]]
repo = 'stevearc/aerial.nvim'
hooks_file = '$BASE_DIR/dein/aerial.lua'

# [[plugins]]
# repo = 'folke/flash.nvim'
# hooks_file = '$BASE_DIR/dein/flash.lua'

[[plugins]]
repo = 'tani/podium'
lua_add = '''
vim.api.nvim_create_user_command("Podium", function()
  local podium = require("podium")
  local lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)
  local output = podium.process(podium.html, table.concat(lines, "\n"))
  vim.api.nvim_buf_set_lines(0, 0, -1, true, vim.split(output, "\n"))
  vim.api.nvim_set_option_value("modified", false, { buf = 0 })
  vim.api.nvim_set_option_value("filetype", "html", { buf = 0 })
end, {})
'''

[[plugins]]
repo = 'lewis6991/hover.nvim'
