[[plugins]]
repo = 'tversteeg/registers.nvim'
lua_add = '''
require('registers').setup {}
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hooks_file = '$BASE_DIR/dpp/gitsigns.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hooks_file = '$BASE_DIR/dpp/lualine.lua'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
hooks_file = ["$BASE_DIR/dpp/barbar.vim", "$BASE_DIR/dpp/barbar.lua"]

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'phaazon/hop.nvim'
hooks_file = '$BASE_DIR/dpp/hop.lua'

[[plugins]]
repo = 'kwkarlwang/bufresize.nvim'

[[plugins]]
repo = 'aserowy/tmux.nvim'
lua_add = '''
require('tmux').setup({
  navigation = {
    enable_default_keybindings = true,
  },
  copy_sync = {
    enable = false,
  },
})
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'zah/nim.vim'

[[plugins]]
repo = 'gamoutatsumi/orgmode'
rev = 'feature/support-emacsclient'
lua_add = '''
require('orgmode').setup_ts_grammar()
require('orgmode').setup {
  org_agenda_files = {'~/Google Drive/マイドライブ/org/*', '~/Repositories/github.com/gamoutatsumi/my-orgs/**/*'},
  org_default_notes_file = '~/Google Drive/マイドライブ/org/refile.org',
}
'''

[[plugins]]
repo = 'levouh/tint.nvim'
lua_add = '''
require('tint').setup {}
'''

[[plugins]]
repo = 'uga-rosa/ccc.nvim'
lua_add = '''
require('ccc').setup {}
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
lua_add = '''
  require('notify').setup {
    background_colour = "#000000",
  }
'''

[[plugins]]
repo = 'monaqa/dial.nvim'
hooks_file = ['$BASE_DIR/dpp/dial.vim']

[[plugins]]
repo = 'ray-x/guihua.lua'

[[plugins]]
repo = 'ruifm/gitlinker.nvim'
lua_add = '''
require('gitlinker').setup()
'''

[[plugins]]
repo = 'stevearc/aerial.nvim'
hooks_file = '$BASE_DIR/dpp/aerial.lua'

[[plugins]]
repo = 'tani/podium'
lua_add = '''
vim.api.nvim_create_user_command("Podium", function()
  local podium = require("podium")
  local lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)
  local output = podium.process(podium.html, table.concat(lines, "\n"))
  vim.api.nvim_buf_set_lines(0, 0, -1, true, vim.split(output, "\n"))
  vim.api.nvim_set_option_value("modified", false, { buf = 0 })
  vim.api.nvim_set_option_value("filetype", "html", { buf = 0 })
end, {})
'''

[[plugins]]
repo = 'uga-rosa/translate.nvim'
lua_add = '''
require("translate").setup {
   default = {
      command = "google",
      output = "floating",
      parse_after = "head"
   }
}
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hooks_file = ["$BASE_DIR/dpp/indent_blankline.lua"]

[[plugins]]
repo = 'numToStr/Comment.nvim'
hooks_file = ['$BASE_DIR/dpp/comment.lua']

[[plugins]]
repo = 'bakpakin/Fennel'
rev = '1.3.1'
rtp = 'nvim'
build = 'make LUA="nvim -ll" fennel.lua && mv fennel.lua nvim/lua/fennel.lua'

[[plugins]]
repo = 'j-hui/fidget.nvim'
rev = 'v1.3.0'
hooks_file = ['$BASE_DIR/dpp/fidget.lua']

[[plugins]]
repo = 'CopilotC-Nvim/CopilotChat.nvim'
lua_add = '''
require('CopilotChat').setup {
  language = 'Japanese'
}
'''
