[[plugins]]
repo = 'tversteeg/registers.nvim'
lua_post_source = '''
require('registers').setup {}
'''

[[plugins]]
repo = 'folke/which-key.nvim'

# [[plugins]]
# repo = 'kevinhwang91/nvim-hlslens'
# hook_add = '''
# noremap <silent> n <Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>
# noremap <silent> N <Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>
# noremap * *<Cmd>lua require('hlslens').start()<CR>
# noremap # #<Cmd>lua require('hlslens').start()<CR>
# noremap g* g*<Cmd>lua require('hlslens').start()<CR>
# noremap g# g#<Cmd>lua require('hlslens').start()<CR>
# nnoremap <silent> <Esc><Esc> <Cmd>nohlsearch<CR>
# '''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hooks_file = '$BASE_DIR/dein/gitsigns.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hooks_file = '$BASE_DIR/dein/lualine.lua'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
  nnoremap <silent> <C-s> <Cmd>BufferPick<CR>
  nnoremap <silent> <S-TAB> <Cmd>BufferPrevious<CR>
  nnoremap <silent> <TAB> <Cmd>BufferNext<CR>
  nnoremap <silent> <A-1> :BufferGoto 1<CR>
  nnoremap <silent> <A-2> :BufferGoto 2<CR>
  nnoremap <silent> <A-3> :BufferGoto 3<CR>
  nnoremap <silent> <A-4> :BufferGoto 4<CR>
  nnoremap <silent> <A-5> :BufferGoto 5<CR>
  nnoremap <silent> <A-6> :BufferGoto 6<CR>
  nnoremap <silent> <A-7> :BufferGoto 7<CR>
  nnoremap <silent> <A-8> :BufferGoto 8<CR>
  nnoremap <silent> <A-9> :BufferLast<CR>
'''

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'phaazon/hop.nvim'
hook_post_source = '''
lua require'hop'.setup()
'''
lua_add = '''
vim.keymap.set('n', 'gff', require'hop'.hint_words)
'''

[[plugins]]
repo = 'b3nj5m1n/kommentary'
lua_post_source = '''
require('kommentary.config').configure_language("typescriptreact", {
  single_line_comment_string = "//",
  multi_line_comment_strings = {"{/*", "*/}"}
})
'''

[[plugins]]
repo = 'kwkarlwang/bufresize.nvim'

[[plugins]]
repo = 'aserowy/tmux.nvim'
lua_post_source = '''
require('tmux').setup({
  navigation = {
    enable_default_keybindings = true,
  },
  copy_sync = {
    enable = false,
  },
})
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'zah/nim.vim'

[[plugins]]
repo = 'gamoutatsumi/orgmode'
rev = 'feature/support-emacsclient'
lua_post_source = '''
require('orgmode').setup_ts_grammar()
require('orgmode').setup {
  org_agenda_files = {'~/Google Drive/マイドライブ/org/*', '~/Repositories/github.com/gamoutatsumi/my-orgs/**/*'},
  org_default_notes_file = '~/Google Drive/マイドライブ/org/refile.org',
}
'''

[[plugins]]
repo = 'levouh/tint.nvim'
lua_post_source = '''
require('tint').setup {}
'''

[[plugins]]
repo = 'uga-rosa/ccc.nvim'
lua_post_source = '''
require('ccc').setup {}
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
lua_post_source = '''
  require('notify').setup {
    background_colour = "#000000",
  }
'''

[[plugins]]
repo = 'folke/noice.nvim'
lazy = 1
on_event = ["VimEnter"]
depends = ['nui.nvim', 'nvim-notify']
lua_post_source = '''
  require("noice").setup {
  }
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
rev = 'legacy'
lua_post_source = '''
require('fidget').setup {}
'''

[[plugins]]
repo = 'monaqa/dial.nvim'
lua_add = '''
vim.api.nvim_set_keymap("n", "<C-a>", require("dial.map").inc_normal(), {noremap = true})
vim.api.nvim_set_keymap("n", "<C-x>", require("dial.map").dec_normal(), {noremap = true})
vim.api.nvim_set_keymap("v", "<C-a>", require("dial.map").inc_visual(), {noremap = true})
vim.api.nvim_set_keymap("v", "<C-x>", require("dial.map").dec_visual(), {noremap = true})
vim.api.nvim_set_keymap("v", "g<C-a>", require("dial.map").inc_gvisual(), {noremap = true})
vim.api.nvim_set_keymap("v", "g<C-x>", require("dial.map").dec_gvisual(), {noremap = true})
'''

[[plugins]]
repo = 'ray-x/guihua.lua'

[[plugins]]
repo = 'ruifm/gitlinker.nvim'
lua_post_source = '''
require('gitlinker').setup()
'''

[[plugins]]
repo = 'folke/neodev.nvim'

[[plugins]]
repo = 'stevearc/aerial.nvim'
hooks_file = '$BASE_DIR/dein/aerial.lua'
