[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
lua_post_source = '''
require("plugins.lsp")
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
lazy = 1
on_source = 'ddc.vim'
hook_source = '''
  call ddc#custom#alias('source', 'lsp', 'nvim-lsp')
'''

[[plugins]]
repo = 'jose-elias-alvarez/nvim-lsp-ts-utils'

[[plugins]]
repo='ray-x/go.nvim'
lazy = 1
on_ft = ['go']
lua_post_source = '''
local ok, path = pcall(require, 'nvim-lsp-installer.path')
local gopls_cmd
if ok then
  local install_root_dir = path.concat {vim.fn.stdpath 'data', 'lsp_servers'}
  gopls_cmd = {install_root_dir .. '/go/gopls'}
end
require('go').setup({
  gopls_cmd = gopls_cmd,
  filstruct = 'gopls',
  dap_debug = true,
  dap_debug_gui = true,
})
'''

[[plugins]]
repo='jose-elias-alvarez/null-ls.nvim'
hook_add = '''
function! s:add_to_dotfiles_dict()
  let word = expand("<cword>")
  if word != ''
    execute "silent! !sed -i '$a" . word . "' " . expand('~/.local/share/chezmoi/dot_config/cspell/dotfiles.txt')
    execute "silent! !chezmoi apply"
  endif
endfunction
command! CspellAddDot call s:add_to_dotfiles_dict()
function! s:add_to_local_dict()
  let word = expand("<cword>")
  if word != ''
    execute "silent! !sed -i '$a" . word . "' " . expand('~/.local/share/cspell/user.txt')
    execute "silent! !chezmoi apply"
  endif
endfunction
command! CspellAddLocal call s:add_to_local_dict()
'''

#[[plugins]]
#repo = 'j-hui/fidget.nvim'
#on_source = ['nvim-lspconfig']
#hook_source = '''
#lua << EOF
#  require('fidget').setup()
#EOF
#'''
