[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hooks_file = '$BASE_DIR/dein/nvim_lsp.lua'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
lazy = 1
on_source = 'ddc.vim'
hook_source = '''
  call ddc#custom#alias('source', 'lsp', 'nvim-lsp')
'''

[[plugins]]
repo='ray-x/go.nvim'
lua_post_source = '''
'''

#[[plugins]]
#repo = 'j-hui/fidget.nvim'
#on_source = ['nvim-lspconfig']
#hook_source = '''
#lua << EOF
#  require('fidget').setup()
#EOF
#'''

[[plugins]]
repo = 'nvimdev/lspsaga.nvim'

[[plugins]]
repo = 'yioneko/nvim-vtsls'

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'

[[plugins]]
repo = 'jose-elias-alvarez/typescript.nvim'

[[plugins]]
repo = 'hrsh7th/nvim-gtd'
lua_post_source = '''
require('gtd').setup({})
'''

[[plugins]]
repo = 'b0o/schemastore.nvim'
