[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hooks_file = '$BASE_DIR/dein/nvim_lsp.lua'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
lazy = 1
on_source = 'ddc.vim'
hook_source = '''
  call ddc#custom#alias('source', 'lsp', 'nvim-lsp')
'''

[[plugins]]
repo='ray-x/go.nvim'
lua_post_source = '''
'''

[[plugins]]
repo='jose-elias-alvarez/null-ls.nvim'
hook_add = '''
function! s:add_to_dotfiles_dict()
  let word = expand("<cword>")
  if word != ''
    execute "silent! !sed -i '$a" . word . "' " . expand('~/.local/share/chezmoi/dot_config/cspell/dotfiles.txt')
    execute "silent! !chezmoi apply"
  endif
endfunction
command! CspellAddDot call s:add_to_dotfiles_dict()
function! s:add_to_local_dict()
  let word = expand("<cword>")
  if word != ''
    execute "silent! !sed -i '$a" . word . "' " . expand('~/.local/share/cspell/user.txt')
    execute "silent! !chezmoi apply"
  endif
endfunction
command! CspellAddLocal call s:add_to_local_dict()
'''

#[[plugins]]
#repo = 'j-hui/fidget.nvim'
#on_source = ['nvim-lspconfig']
#hook_source = '''
#lua << EOF
#  require('fidget').setup()
#EOF
#'''

[[plugins]]
repo = 'glepnir/lspsaga.nvim'

[[plugins]]
repo = 'yioneko/nvim-vtsls'

[[plugins]]
repo = 'jay-babu/mason-null-ls.nvim'

[[plugins]]
repo = 'jose-elias-alvarez/typescript.nvim'

[[plugins]]
repo = 'hrsh7th/nvim-gtd'
lua_post_source = '''
require('gtd').setup({})
'''
