[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_post_source = '''
  lua require("plugins.lsp")
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
lazy = 1
on_source = 'ddc.vim'
hook_source = '''
  call ddc#custom#alias('source', 'lsp', 'nvim-lsp')
'''

[[plugins]]
repo = 'jose-elias-alvarez/nvim-lsp-ts-utils'

[[plugins]]
repo='ray-x/go.nvim'
lazy = 1
on_ft = ['go']
hook_source = '''
lua << EOF
  local ok, path = pcall(require, 'nvim-lsp-installer.path')
  local gopls_cmd
  if ok then
    local install_root_dir = path.concat {vim.fn.stdpath 'data', 'lsp_servers'}
    gopls_cmd = {install_root_dir .. '/go/gopls'}
  end
  require('go').setup({
    gopls_cmd = gopls_cmd,
    filstruct = 'gopls',
    dap_debug = true,
    dap_debug_gui = true,
  })
EOF
'''

[[plugins]]
repo='jose-elias-alvarez/null-ls.nvim'
hook_post_source = '''
lua << EOF
  local null_ls = require("null-ls")
  null_ls.setup {
    sources = {
      null_ls.builtins.formatting.prettier.with({
        only_local = "node_modules/.bin",
      }),
      null_ls.builtins.formatting.goimports,
    },
  }
EOF
'''

#[[plugins]]
#repo = 'j-hui/fidget.nvim'
#on_source = ['nvim-lspconfig']
#hook_source = '''
#lua << EOF
#  require('fidget').setup()
#EOF
#'''
