[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hooks_file = '$BASE_DIR/dein/treesitter.lua'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'

[[plugins]]
repo = 'HiPhish/nvim-ts-rainbow2'
