[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hooks_file = '$BASE_DIR/dein/treesitter.lua'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'

[[plugins]]
repo = 'https:gitlab.com/HiPhish/rainbow-delimiters.nvim'
hooks_file = '$BASE_DIR/dein/rainbow.lua'

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
