[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lua_post_source = '''
require('plugins.treesitter_setting')
'''

[[plugins]]
repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
