[".stack/hooks/ghc-install.sh"]
type = "file"
url = "https://raw.githubusercontent.com/haskell/ghcup-hs/master/scripts/hooks/stack/ghc-install.sh"
refreshPeriod = "730h"
executable = true

[".config/git/template/hooks/pre-push"]
type = "file"
url = "https://gist.githubusercontent.com/quintok/815396509ff79d886656b2855e1a8a46/raw/e6770add98e7db57177c16d33be31bfdf2c23042/pre-push"
refreshPeriod = "730h"
executable = true

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"

[".config/alacritty/nightfly.yml"]
type = "file"
url = "https://raw.githubusercontent.com/bluz71/vim-nightfly-colors/master/extras/alacritty.yml"
refreshPeriod = "730h"
