snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git add
    keyword: ga
    snippet: git add {{file}}
  - name: git add all
    keyword: gaa
    snippet: git add --all
  - name: git commit
    keyword: gci
    snippet: git commit
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'
  - name: git commit fixup
    keyword: gcif
    snippet: git commit --fixup {{commit_id}}
  - name: git empty commit
    keyword: gcie
    snippet: git commit --allow-empty -m 'Initial Commit'
  - name: git diff
    keyword: gd
    snippet: git diff {{branch}}
  - name: git diff file
    keyword: gdf
    snippet: git diff -- {{file}}
  - name: git diff branch file
    keyword: gdbf
    snippet: git diff {{branch}} -- {{file}}
  - name: git diff 2 branch
    keyword: gdbb
    snippet: git diff {{branch1}} {{brahcn2}}
  - name: git diff 2 branch file
    keyword: gdbbf
    snippet: git diff {{branch1}} {{brahcn2}} -- {{file}}
  - name: git diff cached
    keyword: gdc
    snippet: git diff --cached
  - name: git diff cached file
    keyword: gdcf
    snippet: git diff --cached -- {{file}}
  - name: git checkout
    keyword: gco
    snippet: git checkout {{branch}}
  - name: git checkout file
    keyword: gcof
    snippet: git checkout -- {{file}}
  - name: git checkout branch file
    keyword: gcobf
    snippet: git checkout {{branch}} -- {{file}}
  - name: git checkout track
    keyword: gcot
    snippet: git checkout --track {{origin_branch}}
  - name: git reset
    keyword: gre
    snippet: git reset {{branch}}
  - name: git reset file
    keyword: gref
    snippet: git reset -- {{file}}
  - name: git reset hard
    keyword: greh
    snippet: git reset --hard {{branch}}
  - name: git stash
    keyword: gst
    snippet: git stash
  - name: git stash list
    keyword: gstl
    snippet: git stash list
  - name: git stash show {{stash}}
    keyword: gsts
    snippet: git stash show {{stash}}
  - name: git stash apply
    keyword: gsta
    snippet: git stash apply {{stash}}
  - name: git stash pop
    keyword: gstp
    snippet: git stash pop {{stash}}
  - name: git stash drop
    keyword: gstd
    snippet: git stash drop {{stash}}
  - name: git rebase squash
    keyword: squash
    snippet: git rebase --interactive --autosquash {{branch}}
  - name: git rebase squash auto
    keyword: squash
    snippet: GIT_EDITOR=cat git rebase --interactive --autosquash {{branch}}
  - name: git main branch
    keyword: main_branch
    snippet: basename "$(git symbolic-ref --short refs/remotes/origin/HEAD)"
  - name: tms
    keyword: t
    snippet: tms
  - name: tmux swap pane
    keyword: ts
    snippet: tmux swap-pane -t
  - name: "null"
    keyword: "null"
    snippet: "> /dev/null 2>&1"
    context:
      lbuffer: '.+\s+'
  - name: stdout to null
    keyword: null1
    snippet: "> /dev/null"
    context:
      lbuffer: '.+\s+'
  - name: stderr to null
    keyword: null2
    snippet: "2> /dev/null"
    context:
      lbuffer: '.+\s+'
  - name: pipe grep
    keyword: "G"
    snippet: "| grep '{{pattern}}'"
    context:
      lbuffer: '\s*'
  - name: pipe head
    keyword: "H"
    snippet: "| head -n "
    context:
      lbuffer: '\s*'
  - name: copy stdout
    keyword: "C"
    snippet: "| pbcopy"
    context:
      lbuffer: '.+\s+'
  - name: pipe less
    keyword: "L"
    snippet: "| less"
    context:
      lbuffer: '.+\s+'
  - name: pipe jq
    keyword: "J"
    snippet: "| jq .{{query}}"
    context:
      lbuffer: '.+\s+'
  - name: pipe gron
    keyword: "JG"
    snippet: " | gron | grep"
    context:
      lbuffer: '.+\s+'
  - name: ungron
    keyword: "UG"
    snippet: " | gron -u"
    context:
      lbuffer: '.+\s+'
  - name: branch
    keyword: B
    snippet: git symbolic-ref --short HEAD
    context: 
      lbuffer: '^git\s+checkout\s+'  
    evaluate: true
  - namme: git switch
    keyword: gsw
    snippet: git switch {{branch}}
  - namme: git switch create
    keyword: gswc
    snippet: git switch -c {{branch}}
completions:
  - name: kill
    patterns: 
      - "^kill( -9)? $"
    sourceCommand: "ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"
  - name: vim
    patterns:
      - "^v(i(m)?)? $"
    sourceCommand: "rg --files --follow --glob '!.git'"
    options:
      --prompt: "'Open File> '"
      --preview-window: "right:50%"
      --preview: "bat --color=always --style=plain {} 2>/dev/null"
    callback: "awk '{print $1}'"
  - name: ssh
    patterns:
      - "^ssh $"
    sourceCommand: "grep '^Host' ~/.ssh/config | awk '{print $2}'"
    options:
      --prompt: "'Connect to> '"
    callback: "awk '{print $1}'"
  - name: cd
    patterns:
      - "^cd $"
    sourceCommand: "fd --type=d"
    options:
      --prompt: "'To> '" 
      --preview-window: "right:50%"
      --preview: "exa --icons -l --no-user"
    callback: "awk '{print $1}'"
