[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
hook_add = '''
  if dein#tap('nvim-lsp-installer') && dein#tap('nvim-lspconfig')
    lua require("plugins.lsp")
  endif
'''

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'

[[plugins]]
repo = 'weilbith/nvim-lsp-smag'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'gamoutatsumi/ddc-emoji'

[[multiple_plugins]]
plugins = [
  'ddc.vim', 'ddc-fuzzy', 'ddc-emoji', 'ddc-nvim-lsp',
  'ddc-around', 'pum.vim', 'denops-popup-preview.vim',
  'neco-vim', 'lexima.vim', 'vim-vsnip',
  'vim-vsnip-integ', 'ddc-cmdline-history'
]
hook_add = '''
  let g:lexima_map_escape = '<Plug>(lexima-escape)'
  let g:lexima_no_default_rules = v:true
  let g:vsnip_snippet_dir = join([$XDG_CONFIG_HOME, 'nvim', 'vsnip'], '/')

  function! PumInit() abort
    imap <silent><expr> <TAB> pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' : vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<TAB>'
    imap <silent><expr> <C-n> pum#visible() ? '<Cmd>call pum#map#select_relative(+1)<CR>' : '<C-n>'
    smap <silent><expr> <TAB> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<TAB>'
    imap <silent><expr> <S-TAB> pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' : vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-TAB>'
    imap <silent><expr> <C-p> pum#visible() ? '<Cmd>call pum#map#select_relative(-1)<CR>' : '<C-p>'
    smap <silent><expr> <S-TAB> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-TAB>'
    inoremap <silent><expr> <CR> pum#visible() ? '<Cmd>call pum#map#confirm()<CR>' : lexima#expand('<LT>CR>', 'i')
    imap <silent><expr> <Esc> pum#visible() ? '<Cmd>call pum#map#cancel()<CR>' : '<Plug>(lexima-escape)'

    autocmd User PumCompleteDone call vsnip_integ#on_complete_done(g:pum#completed_item)
  endfunction

  function! s:ddcinit() abort
    call lexima#set_default_rules()
    call PumInit()
    call ddc#custom#patch_global('completionMenu', 'pum.vim')
    call ddc#custom#patch_global('backspaceCompletion', v:true)
    call ddc#custom#patch_global('autoCompleteEvents',
      \ ['InsertEnter', 'TextChangedI', 'TextChangedP'])
    call ddc#custom#patch_global('sources', ['nvim-lsp', 'file', 'vsnip', 'emoji', 'around'])
    call ddc#custom#patch_global('keywordPattern', '[a-zA-Z_:]\w*')
    call ddc#custom#patch_global('sourceOptions', {
    \ '_': { 'matchers': ['matcher_fuzzy'], 'sorters': ['sorter_fuzzy'], 'converters': ['converter_fuzzy'] },
    \ 'nvim-lsp': { 'mark': 'lsp', 'forceCompletionPattern': '\.\w*|:\w*|->\w*|"\w*', 'ignoreCase': v:true },
    \ 'around': {
    \   'mark': 'A',
    \   'isVolatile': v:true,
    \ },
    \ 'vsnip': {
    \   'mark': 'VS',
    \   'dup': v:true,
    \ },
    \ 'file': {
    \   'mark': 'F',
    \   'isVolatile': v:true,
    \   'forceCompletionPattern': '\S/\S*',
    \ },
    \ 'emoji': {
    \   'mark': 'emoji',
    \   'matchers': ['emoji'],
    \   'sorters': [],
    \ },
    \ })

    call ddc#enable()
    call popup_preview#enable()
  endfunction

  function! CommandlinePre() abort
    let s:prev_buffer_config = ddc#custom#get_buffer()

    call ddc#custom#patch_buffer('sources', ['necovim', 'cmdline-history'])
    call ddc#custom#patch_buffer('autoCompleteEvents', ['CmdlineChanged'])
    call ddc#custom#patch_buffer('sourceOptions', {
    \ '_': {'matchers': ['matcher_head'], 'sorters': ['sorter_rank'], 'converters': []},
    \ 'necovim': {'mark': 'V', 'minAutoCompleteLength': 3, 'ignoreCase': v:true},
    \ 'cmdline-history': {'mark': 'history', 'minAutoCompleteLength': 3},
    \ })

    call ddc#enable_cmdline_completion()

    cmap <silent><expr> <TAB> pum#visible() ? '<Cmd>call pum#map#insert_relative(+1)<CR>' : '<TAB>'
    cmap <silent><expr> <S-TAB> pum#visible() ? '<Cmd>call pum#map#insert_relative(-1)<CR>' : '<C-h>'
    cmap <silent><expr> <CR> pum#visible() ? '<Cmd>call pum#map#confirm()<CR>' : '<CR>'

    autocmd CmdlineLeave * ++once call CommandlinePost()
  endfunction

  function! CommandlinePost() abort
    cunmap <TAB>
    cunmap <S-TAB>
    cunmap <CR>
    call ddc#custom#set_buffer(s:prev_buffer_config)
  endfunction

  nnoremap : <Cmd>call CommandlinePre()<CR>:
  nnoremap ; <Cmd>call CommandlinePre()<CR>:

  autocmd User DenopsReady call s:ddcinit()
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
