[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_lua = ['lspconfig']

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_lua = ['nvim-lsp-installer']
hook_add = '''
  lua require("plugins.lsp")
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
depends = ['nvim-lspconfig']
on_source = 'ddc.vim'
hook_source = '''
  call ddc#custom#patch_global('sources', ['nvim-lsp', 'file', 'vsnip', 'emoji', 'around'])
  call ddc#custom#patch_global('sourceOptions', {
  \ 'nvim-lsp': {
  \   'mark': 'lsp',
  \   'forceCompletionPattern': '\.\w*|:\w*|->\w*|"\w*',
  \   'ignoreCase': v:true,
  \   'isVolatile': v:true
  \ },
  \ })
'''

[[plugins]]
repo = 'jose-elias-alvarez/nvim-lsp-ts-utils'
on_lua = ['nvim-lsp-ts-utils']
