[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lazy = 1
on_lua = ['nvim-treesitter']
hook_add = '''
lua require('plugins.treesitter_setting')
'''

[[plugins]]
# repo = 'windwp/nvim-ts-autotag'
repo = 'gamoutatsumi/nvim-ts-autotag'
rev = 'fix/get-win-cursor'
depends = ['nvim-treesitter']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'
