[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_source = '''
lua require('plugins.treesitter_setting')
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-refactor'

# [[plugins]]
# repo = 'p00f/nvim-ts-rainbow'
