name: aqua

on:
  push:
    branches:
      - master
    paths:
      - 'dot_config/aqua/aqua.yaml'
      - '.github/workflows/aqua.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'dot_config/aqua/aqua.yaml'
      - '.github/workflows/aqua.yaml'

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: cache ~/.aqua
        uses: actions/cache@v3
        with:
          path: |
            ~/.aqua/pkgs
            ~/.aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('dot_config/aqua/aqua.yaml') }}

      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.33.0
      - run: aqua -c dot_config/aqua/aqua.yaml i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
