name: aqua

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.21.6" # renovate: depName=golang/go 
      - name: cache ~/.aqua
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.aqua/pkgs
            ~/.aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('dot_config/aqua/aqua.yaml') }}

      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.21.3
      - run: aqua -c dot_config/aqua/aqua.yaml i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AQUA_POLICY_CONFIG: "dot_config/aqua/aqua-policy.yaml"
