name: aqua

on:
  push:
    branches:
      - master
    paths:
      - 'dot_config/aqua/aqua.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'dot_config/aqua/aqua.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache ~/.aqua
        uses: actions/cache@v3
        with:
          path: |
            ~/.aqua/pkgs
            ~/.aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('dot_config/aqua/aqua.yaml') }}

      - uses: aquaproj/aqua-installer@main
        with:
          aqua_version: v1.6.0 # renovate: depName=aquaproj/aqua
      - run: aqua -c dot_config/aqua/aqua.yaml i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
