name: CI

on: 
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: apt-get update && apt-get install -y git zsh unzip
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install dotfiles
        run: ./deploy.sh dotfiles
      - name: Test zshrc
        run: zsh -i -c "[[ $? = 0 ]] && exit 0 || exit 1"

  centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: yum install -y git zsh unzip
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install dotfiles
        run: ./deploy.sh dotfiles
      - name: Test zshrc
        run: zsh -i -c "[[ $? = 0 ]] && exit 0 || exit 1"

  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git zsh unzip
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install dotfiles
        run: ./deploy.sh dotfiles
      - name: Test zshrc
        run: zsh -i -c "[[ $? = 0 ]] && exit 0 || exit 1"

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update packages
        run: brew update
      - name: Install required packages
        run: brew install git coreutils unzip
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install dotfiles
        run: ./deploy.sh dotfiles
      - name: Test zshrc
        run: zsh -i -c "[[ $? = 0 ]] && exit 0 || exit 1"

  lint:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Update packages
        run: apt-get update
      - name: Install packages for install repository
        run: apt-get install -y git
      - name: Install required repository
        run: apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
      - name: Install required packages
        run: apt-get udpate; apt-get install -y shellcheck
      - name: Execute shellcheck
        run: test $(shellcheck  -f gcc ~/.zshrc ~/.zsh/rc/* | grep -v "SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148\|SC1090\|SC1117\|SC2206\|SC1009\|SC2016\|SC2046\|SC2154" | tee -a /dev/stderr | wc -l) -le 1
