name: aqua

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.23.2" # renovate: depName=golang/go 
      - run: |
          rustup set profile minimal
          rustup install stable
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
      - name: cache ~/.aqua
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: |
            ~/.aqua/pkgs
            ~/.aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('dot_config/aqua/aqua.yaml') }}

      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.36.1
      - run: aqua -c dot_config/aqua/aqua.yaml i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AQUA_POLICY_CONFIG: "dot_config/aqua/aqua-policy.yaml"
