name: aqua

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: "1.23.2" # renovate: depName=golang/go 
      - run: |
          rustup set profile minimal
          rustup install stable
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: cache ~/.aqua
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            ~/.aqua/pkgs
            ~/.aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('dot_config/aqua/aqua.yaml') }}

      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.37.0
      - run: aqua -c dot_config/aqua/aqua.yaml i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AQUA_POLICY_CONFIG: "dot_config/aqua/aqua-policy.yaml"
