name: pru
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  pru:
    name: pru
    runs-on: ubuntu-latest
    steps:
      - uses: winebarrel/pru-action@e3ac0c53c6155fc68fc8d24f91dc5c8ee58e19c0 # v0.3.0
        with:
          paths: |
            **/*
